### ISSUE TITLE
Could not find toolchain file: /tools/cmake/toolchain-esp32s3.cmake

### ISSUE THREAD

**Issue by Owizmi** [libmcu/madi#1]
Host Environment

OS: Windows 11
Compiler: VSCode

Failure logs

[main] Building folder: madi-main 
[main] Configuring project: madi-main 
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE -DIDF_TARGET=esp32s3 -DBOARD=madi_esp32 -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 -SC:/Users/kimjw/Downloads/madi-main/madi-main -BC:/Users/kimjw/Downloads/madi-main/madi-main/build/madi_esp32 -G Ninja
[cmake] CMake Error at C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineSystem.cmake:154 (message):
[cmake]   Could not find toolchain file: /tools/cmake/toolchain-esp32s3.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:21 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[proc] The command: C:\msys64\mingw64\bin\cmake.EXE -DIDF_TARGET=esp32s3 -DBOARD=madi_esp32 -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 -SC:/Users/kimjw/Downloads/madi-main/madi-main -BC:/Users/kimjw/Downloads/madi-main/madi-main/build/madi_esp32 -G Ninja exited with code: 1

- ESP-IDF 다시 설치해도 동일함.
- MSYS2 다시 설치해도 동일함.

**Comment by onkwon** [comment]
`[cmake] Could not find toolchain file: /tools/cmake/toolchain-esp32s3.cmake` 이 에러 메시지를 보면 IDF_PATH 환경 설정이 export 안된 것 같습니다.

기존 환경이 어떤 이유로 변경된 것 같은데요. `echo $IDF_PATH` 해보시고 아무런 출력이 없다면 환경설정을 추가해야 하고, 출력이 나온다면 아래와 같이 입력해서 빌드되는지 한번 확인해보면 어떨까 싶네요:

`C:\msys64\mingw64\bin\cmake.EXE -DIDF_PATH=$IDF_PATH -DIDF_TARGET=esp32s3 -DBOARD=madi_esp32 -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 -SC:/Users/kimjw/Downloads/madi-main/madi-main -BC:/Users/kimjw/Downloads/madi-main/madi-main/build/madi_esp32 -G Ninja`

**Comment by onkwon** [comment]
https://www.youtube.com/playlist?list=PLhdIB9v89ue2Gs9KZNzTYOf4VMgF81Le3

**Comment by onkwon** [comment]
ESP32의 경우 ESP-IDF 확장 프로그램의 빌드 버튼을 눌러야 빌드가 됩니다. CMake 확장 프로그램의 빌드 버튼을 누르면 환경변수가 설정되어 있지 않기 때문에 위와 같은 오류가 발생합니다.

이슈는 닫겠습니다. 계속 문제가 발생하면 다시 열어주세요.
